hmrc/self-assessment-api-legacy

- project/MicroServiceBuild.scala
> MTDSA-3479 - Change project name to self-assessment-api-legacy

- conf/application.conf
> [MTDSA-3464] add mongodb uri

- app/uk/gov/hmrc/r2/selfassessmentapi/resources/PropertiesAnnualSummaryResource.scala
> MTDSA-3515 Removed condition block for case 404

- project/MicroService.scala
>  Mtdsa 3581 Set default http port for project

- project/MicroServiceBuild.scala
- project/plugins.sbt
> MTDSA-3701: Updated dependencies

- project/MicroServiceBuild.scala
> MTDSA-3705 - update reactivemongo dependency

- project/MicroServiceBuild.scala
> MTDSA-3788 Updated all minor dependencies.

- app/uk/gov/hmrc/kenshoo/monitoring/MonitoredWSHttp.scala
- project/MicroServiceBuild.scala
> MTDSA-4046 Upgrade conflicts fixed

- conf/application.conf
> Update headers whitelist

- conf/application.conf
> Temporarily remove headers whitelist

- conf/application.conf
> Remove added whitelist headers

- app/uk/gov/hmrc/kenshoo/monitoring/MonitoredWSHttp.scala
- project/MicroServiceBuild.scala
> MTDSA-4089 Upgraded bootstrap and fixed tests

- app/uk/gov/hmrc/r2/selfassessmentapi/resources/wrappers/Response.scala
> [MK] add correlation ID to error log for Production monitoring

- app/uk/gov/hmrc/r2/selfassessmentapi/resources/wrappers/Response.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
> Add logging

- conf/application.conf
- conf/logback.xml
> [MK] manually whitelist content type to add to header carrier

- app/uk/gov/hmrc/selfassessmentapi/connectors/TaxCalculationConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/EmptyJsonBody.scala
> Updated retrieveTaxCalc

- build.sbt
> disable junit xml reporting

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
> [MTDSA-4738] ITs no longer run UTs

- project/AppDependencies.scala
- project/plugins.sbt
> MTDSA-5064 update dependencies

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> MTDSA-7338 update dependencies

- app/uk/gov/hmrc/r2/selfassessmentapi/config/AppContext.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/services/AuthorisationService.scala
- app/uk/gov/hmrc/selfassessmentapi/config/AppContext.scala
- app/uk/gov/hmrc/selfassessmentapi/services/AuthorisationService.scala
- conf/application.conf
- func/uk/gov/hmrc/selfassessmentapi/AuthorisationServiceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-8313] implement confidence level auth check

- conf/application.conf
> Update des host
